// src/views/find-differences.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { DiffModeEnum, DiffView } from "@git-diff-view/vue";
import { generateDiffFile } from "@git-diff-view/file";

const oldText = ref("");
const newText = ref("");

const diffFile = computed(() => {
  let oldValue = (oldText.value || "").replace(/\r\n/g, "\n");
  let newValue = (newText.value || "").replace(/\r\n/g, "\n");
  if (oldValue === newValue) return null;

  if (oldValue && !oldValue.endsWith("\n")) oldValue += "\n";
  if (newValue && !newValue.endsWith("\n")) newValue += "\n";

  const file = generateDiffFile("oldText", oldValue, "newText", newValue, "plaintext", "plaintext");
  file.initRaw();
  return file;
});
</script>

<template>
  <div>
    <h2 class="display-6">Diff Text</h2>
    <div class="row">
      <div class="col-sm-6">
        <label for="oldText" class="form-label">Old</label>
        <textarea id="oldText" v-model="oldText" class="form-control" rows="10" />
      </div>
      <div class="col-sm-6">
        <label for="newText" class="form-label">New</label>
        <textarea id="newText" v-model="newText" class="form-control" rows="10" />
      </div>
      <div class="col-sm-12">
        <label for="diffText" class="form-label">Diff</label>
        <div id="diffText" class="diff-container">
          <DiffView v-if="diffFile" :diff-file="diffFile" :diff-view-mode="DiffModeEnum.Unified" />
          <div v-else class="p-3 text-center text-muted">No differences found</div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.diff-container {
  height: 18em;
  border-radius: 5px;
  border: solid 1px #ccc;
  overflow-y: scroll;
}
</style>

// find-differences.tsx
import * as React from "react";
import { DiffView, DiffModeEnum } from "@git-diff-view/react";
import { generateDiffFile } from "@git-diff-view/file";

const style: React.CSSProperties = {
  height: "18em",
  borderRadius: "5px",
  border: "solid 1px #ccc",
  overflowY: "scroll",
};

export default function DiffText() {
  const [state, setState] = React.useState({ newText: "", oldText: "" });
  const handleInput =
    (key: "newText" | "oldText") => (event: React.ChangeEvent<HTMLTextAreaElement>) =>
      setState({ ...state, [key]: event.target.value });

  const diffFile = React.useMemo(() => {
    let oldText = (state.oldText || "").replace(/\r\n/g, "\n");
    let newText = (state.newText || "").replace(/\r\n/g, "\n");
    if (oldText === newText) return null;

    // Ensure they end with newline to avoid mismatch warnings in the viewer
    if (oldText && !oldText.endsWith("\n")) oldText += "\n";
    if (newText && !newText.endsWith("\n")) newText += "\n";

    const file = generateDiffFile(
      "oldText",
      oldText,
      "newText",
      newText,
      "plaintext",
      "plaintext",
    );
    file.initRaw();
    return file;
  }, [state.oldText, state.newText]);

  return (
    <div>
      <h2>Diff Text</h2>
      <div className="row">
        <div className="col-sm-6">
          <label htmlFor="oldText" className="form-label">
            Old
          </label>
          <textarea
            name="oldText"
            className="form-control"
            onChange={handleInput("oldText")}
            rows={10}
          />
        </div>
        <div className="col-sm-6">
          <label htmlFor="newText" className="form-label">
            New
          </label>
          <textarea
            name="newText"
            className="form-control"
            onChange={handleInput("newText")}
            rows={10}
          />
        </div>
        <div className="col-sm-12">
          <label htmlFor="diffText" className="form-label">
            Diff
          </label>
          <div id="diffText" style={style}>
            {diffFile ? (
              <DiffView diffFile={diffFile} diffViewMode={DiffModeEnum.Unified} />
            ) : (
              <div className="p-3 text-center text-muted">No differences found</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
