// src/views/replace-text.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { DiffModeEnum, DiffView } from "@git-diff-view/vue";
import { generateDiffFile } from "@git-diff-view/file";

const text = ref("");
const replaceText = ref("");
const search = ref("");

const result = computed(() => {
  try {
    if (!search.value) return text.value;
    return text.value.replace(new RegExp(search.value, "g"), replaceText.value);
  } catch {
    return text.value;
  }
});

const diffFile = computed(() => {
  let oldText = (text.value || "").replace(/\r\n/g, "\n");
  let newText = (result.value || "").replace(/\r\n/g, "\n");
  if (oldText === newText) return null;

  if (oldText && !oldText.endsWith("\n")) oldText += "\n";
  if (newText && !newText.endsWith("\n")) newText += "\n";

  const file = generateDiffFile("Deleted", oldText, "Added", newText, "plaintext", "plaintext");
  file.initRaw();
  return file;
});
</script>

<template>
  <div>
    <h2>Replace Text</h2>
    <label for="search" class="form-label">Search</label>
    <input id="search" v-model="search" class="form-control" />
    <label for="replace" class="form-label">Replace</label>
    <input id="replace" v-model="replaceText" class="form-control" />
    <div class="row">
      <div class="col-sm-6">
        <label for="text" class="form-label">Input</label>
        <textarea id="text" v-model="text" class="form-control" rows="20" />
      </div>
      <div class="col-sm-6">
        <label for="result" class="form-label">Output</label>
        <textarea id="result" class="form-control" :value="result" readonly rows="20" />
      </div>
    </div>
    <div v-if="diffFile" class="mt-5">
      <DiffView :diff-file="diffFile" :diff-view-mode="DiffModeEnum.Split" />
    </div>
  </div>
</template>

// replace-text.jsx
import * as React from "react";
import ReactDiffViewer from "react-diff-viewer";

export default function ReplaceText() {
	const [state, setState] = React.useState({
		text: "",
		replace: "",
		search: "",
	});

	const handleInput = (key) => (event) => {
		setState({ ...state, [key]: event.target.value });
	};

	const result = (() => {
		try {
			return state.text.replace(new RegExp(state.search, "g"), state.replace);
		} catch {
			return state.text;
		}
	})();

	return (
		<div>
			<h2>Replace Text</h2>
			<label htmlFor="search" className="form-label">
				Search
			</label>
			<input
				name="search"
				className="form-control"
				onInput={handleInput("search")}
			/>
			<label htmlFor="replace" className="form-label">
				Replace
			</label>
			<input
				name="replace"
				className="form-control"
				onInput={handleInput("replace")}
			/>
			<div className="row">
				<div className="col-sm-6">
					<label htmlFor="text" className="form-label">
						Input
					</label>
					<textarea
						name="text"
						className="form-control"
						onInput={handleInput("text")}
						rows="20"
					/>
				</div>
				<div className="col-sm-6">
					<label htmlFor="result" className="form-label">
						Output
					</label>
					<textarea
						name="result"
						className="form-control"
						value={result}
						readOnly
						rows="20"
					/>
				</div>
			</div>
			{state.text !== result && (
				<div className="mt-5">
					<ReactDiffViewer
						oldValue={state.text}
						newValue={result}
						leftTitle="Deleted"
						rightTitle="Added"
					/>
				</div>
			)}
		</div>
	);
}
