// src/views/unicode-to-latex.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import jsonRaw from "../assets/unicode_latex_unicodemath.json";

const json = jsonRaw as [string, string, string][];
const input = ref("");

function replace(value: string) {
  let val = value;
  for (const [, char, latex] of json) {
    if (char !== "" && char.charCodeAt(0) > 127 && latex.length > 2) {
      val = val.replaceAll(char, `$${latex}$`);
    }
  }
  return val.replaceAll(/\$\$\$/g, "$");
}

const output = computed(() => replace(input.value));
</script>

<template>
  <div>
    <h2>Unicode To LaTeX</h2>
    <div class="row">
      <div class="col-sm-6">
        <textarea v-model="input" class="form-control mt-3" rows="20" />
      </div>
      <div class="col-sm-6">
        <textarea class="form-control mt-3" :value="output" readonly rows="20" />
      </div>
    </div>
  </div>
</template>

// unicode-to-latex.jsx
import * as React from "react";
import json from "./unicode_latex_unicodemath.json" with { type: "json" };

export default function UnicodeToLaTeX() {
	const [state, setState] = React.useState({ value: "" });

	function replace(str) {
		let val = str;
		for (const [_, char, latex] of json) {
			if (char !== "" && char.charCodeAt(0) > 127 && latex.length > 2) {
				val = val.replaceAll(char, `$${latex}$`);
			}
		}
		return val.replaceAll(/\$\$/g, "");
	}

	const handleInput = (event) =>
		setState({ ...state, value: event.target.value });

	return (
		<div>
			<h2>Unicode To LaTeX</h2>
			<div className="row">
				<div className="col-sm-6">
					<textarea
						className="form-control mt-3"
						onInput={handleInput}
						rows="20"
					/>
				</div>
				<div className="col-sm-6">
					<textarea
						className="form-control mt-3"
						value={replace(state.value)}
						readOnly
						rows="20"
					/>
				</div>
			</div>
		</div>
	);
}
